document.writeln("<script src='" + urldepth + "menu_26_10_2005.js' language='javascript' type='Text\/Javascript'>");
document.writeln("<\/script>");

document.writeln("<script src='" + urldepth + "menu3.asp' language='javascript' type='Text\/Javascript'>");
document.writeln("<\/script>");

document.writeln("<script language='javascript' type='Text\/Javascript'><!--");
document.writeln("\/\/--><\/script>");
